[build]
  base = "."
  command = "npm install --prefix artifacts/feltly --legacy-peer-deps && npm run build --prefix artifacts/feltly"
  publish = "artifacts/feltly/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
