const colors = {
  light: {
    text: "#1A1828",
    tint: "#9E7CCC",
    background: "#F5F3FA",
    foreground: "#1A1828",
    card: "#FFFFFF",
    cardForeground: "#1A1828",
    primary: "#9E7CCC",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9F6",
    secondaryForeground: "#1A1828",
    muted: "#EDE9F6",
    mutedForeground: "#6B667A",
    accent: "#9E7CCC",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E0DBEF",
    input: "#E0DBEF",
    surface: "#FFFFFF",
    overlay: "rgba(0,0,0,0.4)",
  },
  dark: {
    text: "#F0EEF8",
    tint: "#9E7CCC",
    background: "#0E0D14",
    foreground: "#F0EEF8",
    card: "#1A1828",
    cardForeground: "#F0EEF8",
    primary: "#9E7CCC",
    primaryForeground: "#FFFFFF",
    secondary: "#252336",
    secondaryForeground: "#C8C4DC",
    muted: "#252336",
    mutedForeground: "#8E8BA8",
    accent: "#9E7CCC",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2840",
    input: "#2A2840",
    surface: "#1A1828",
    overlay: "rgba(0,0,0,0.6)",
  },
  radius: 12,
  moods: {
    calm:       { accent: "#5CB8C8", bg: "#0D2A30", label: "Calm",       emoji: "🌊" },
    cozy:       { accent: "#D4874A", bg: "#2D1A0A", label: "Cozy",       emoji: "🕯️" },
    melancholy: { accent: "#7A8EBF", bg: "#0D1128", label: "Melancholy", emoji: "🌧️" },
    intense:    { accent: "#BF3D52", bg: "#2D0A10", label: "Intense",    emoji: "🔥" },
    dreamy:     { accent: "#9E7CCC", bg: "#1A0D30", label: "Dreamy",     emoji: "✨" },
    joyful:     { accent: "#D4A832", bg: "#2D2208", label: "Joyful",     emoji: "🌻" },
    mysterious: { accent: "#5C5C9E", bg: "#0D0D2D", label: "Mysterious", emoji: "🌙" },
  } as const,
};

export type MoodKey = keyof typeof colors.moods;

export default colors;
