const colors = {
  light: {
    text: "#2A1F14",
    tint: "#9E7CCC",
    background: "#EDE8DE",
    foreground: "#2A1F14",
    card: "#F2ECE3",
    cardForeground: "#2A1F14",
    primary: "#9E7CCC",
    primaryForeground: "#FFFFFF",
    secondary: "#E4DDD4",
    secondaryForeground: "#2A1F14",
    muted: "#E4DDD4",
    mutedForeground: "#8B8075",
    accent: "#9E7CCC",
    accentForeground: "#FFFFFF",
    destructive: "#C0392B",
    destructiveForeground: "#FFFFFF",
    border: "#D9D0C4",
    input: "#D9D0C4",
    surface: "#F2ECE3",
    overlay: "rgba(42,31,20,0.4)",
  },
  dark: {
    text: "#F0EEF8",
    tint: "#9E7CCC",
    background: "#0E0D14",
    foreground: "#F0EEF8",
    card: "#1A1828",
    cardForeground: "#F0EEF8",
    primary: "#9E7CCC",
    primaryForeground: "#FFFFFF",
    secondary: "#252336",
    secondaryForeground: "#C8C4DC",
    muted: "#252336",
    mutedForeground: "#8E8BA8",
    accent: "#9E7CCC",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2840",
    input: "#2A2840",
    surface: "#1A1828",
    overlay: "rgba(0,0,0,0.6)",
  },
  radius: 12,
  moods: {
    calm:       { accent: "#5CB8C8", bg: "#E8F5F7", label: "Calm",       emoji: "🌊" },
    cozy:       { accent: "#D4874A", bg: "#FBF0E6", label: "Cozy",       emoji: "🕯️" },
    melancholy: { accent: "#7A8EBF", bg: "#EEF0F8", label: "Melancholy", emoji: "🌧️" },
    intense:    { accent: "#BF3D52", bg: "#FBE9EC", label: "Intense",    emoji: "🔥" },
    dreamy:     { accent: "#9E7CCC", bg: "#F0EBF8", label: "Dreamy",     emoji: "✨" },
    joyful:     { accent: "#D4A832", bg: "#FBF5E0", label: "Joyful",     emoji: "🌻" },
    mysterious: { accent: "#5C5C9E", bg: "#EEEEF8", label: "Mysterious", emoji: "🌙" },
  } as const,
};

export type MoodKey = keyof typeof colors.moods;

export default colors;
